### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Villee00/F1-history#1]
# Full Stack projektin katselmointi

Terve @Villee00! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

Selasin kausia, kisoja ja kuskeja.

### Kokemus

- F1-sovelluksella on selkeä ja tyylikkäästi käyttöliittymä, hienoa työtä! 🏆
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi
- Etusivun "Seasons"-valikko voisi ehkä olla [Select](https://mui.com/components/selects/)- komponentti, niin se ei veisi sivulla niin paljon tilaa
- Hyvä, että "Drivers"-sivulla on sivutus, kun kuskeja on niin paljon. Hakutoiminallisuus kuskin nimen perusteella voisi olla käteävä
- Yksittäisen kuskin näkymän kisataulukossa erittäin kattavat järjestysvaihtoehdot
- Material UI:n komponentteja on hyödynnetty käyttöliittymässä erittäin hyvin

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä! Ehkä kaikki komponentit voisivat sijaita `components`-hakemistossa, tai jos haluaa erikseen erotella `Router`-komponenteissa käytetyt komponentit ne voisi laittaa omaan hakemistoon kuten `pages`
- GraphQL-queryt on tallennettu vakiomuuttujiin ja niissä on hyödynnetty fragmentteja, hienoa!
- Eikö [tämä](https://github.com/Villee00/F1-history/blob/main/frontend/src/components/AppBar.js#L18) voisi tulla polkuparametrista?
- Toiminallisuutta on pilkottu järkevästi pieniin komponentteihin, joka parantaa koodin luettavuutta huomattavasti
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- GraphQL-skeeman määrittely on eritelty tiedostoihin järkevästi
- API-kutsut on abstrahoitu omiksi palveluiksi. Tämä selkeyttää koodia ja parantaa sen ylläpidettävyyttä

## Kokonaisuus

Erittäin hieno, ulkoisia API-rajapintoja hyöydyntävä sovellus! Sovelluksen käyttöliittymässä hyödynnetään hyvin Material UI:n komponentteja, jonka seurauksena on tyylikäs lopputulos. Kaikki sovelluksen toiminallisuus oli helppokäyttöistä, eikä katselmoinnin aikana ilmennyt bugeja tai käytettävyysongelmia. Projektin koodi on hyvin organisoitua ja laadukasta. API-kutsut on abstrahoitu backendin puolella niin, että koodi pysyy selkeänä ja ylläpidettävänä. Hyvää työtä!

**Comment by Villee00** [comment]
Kiitos todella kattavasta katselmoinnista! Käytän parannusehdotuksia vielä tässä projektissa, kun ehdin laajentamaan tämän 10op laajuiseksi!
