### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [Villee00/F1-history#2]
Terve @Villee00! Tässä lyhyt katselmointi laajennetusta projektista, joka on jatkoa #1 katselmoinnille. Muutama kommentti projektin nykytilasta:

- Käytettävyyteen liittyvät ongelmat, jotka mainitsin edellisessä katselmoinnissa on korjattu kokonaan. Loistavaa!
- Frontend-puolen koodi on nyt organisoitu erittäin selkeästi
- Dockeria on hyödynnetty hyvin sekä kehitys-, että tuotanympäristön kanssa. Samoin Nginxia reverse proxyn kanssa.
- Jos mitään parannettavaa yrittää keksiä, niin ehkä CI-putki voisi olla hyvä lisä projektiin (lisää tästä kurssin [osassa 11](https://fullstackopen.com/en/part11))

Hyvää työtä!

**Comment by Villee00** [comment]
Kiitos kommenteista!
